### ISSUE TITLE
3/29 NodeSchool Event Planning

### ISSUE THREAD

**Issue by jasonrhodes** [nodeschool/baltimore#10]
Hey friends, I need help getting this together. Here are some tasks you could volunteer for.

##### Anyone! Help us out!
* Updating the website front page with info for the new event (create a pull request editing the site here in this repo in the gh-pages branch)
* Writing a draft of the email to go out to everyone announcing the new event
* Wrangling up mentors
* Finding more sponsors—Message Systems and eMoxie are great sponsors but I want to add more if there are others who are interested

##### Higher trust jobs (I'd prefer if I know you for these, at least for now)
* Send email campaigns (via MailChimp), update the email lists
* Set up the ti.to event/ticketing page

**Comment by jasonrhodes** [comment]
This is picking up from the conversation in #9 ...

**Comment by jasonrhodes** [comment]
Other things I'm thinking about:

* Prereqs page on our website, I'm going to build this out and suggest videos, tutorials, tools and skills that are recommended if you are coming to NodeSchool.
* 12-1pm "Setup Hour" for new people or people who want some assistance with setup or who have questions about any of hte prereqs mentioned above. We may need to provide some kind of lunch for this to work, which gets complicated.

**Comment by richleland** [comment]
Hey @jasonrhodes I can take on the tito stuff and update the front page, just shoot me any tito info I need and I'll get a PR in for the page update.

**Comment by arei** [comment]
I'm in to mentor...

**Comment by unstoppablecarl** [comment]
I am interested in mentoring again.

**Comment by dheles** [comment]
I can mentor, review and test the material we intend to present.

**Comment by apechimp** [comment]
I can mentor.

**Comment by RyanSpahn** [comment]
Hi everyone and thank you Jason for inviting me to this group.

As a design coder (skilled in all things HTML/CSS/Bootstrap/Photoshop) who is looking to learn Javascript/become a logic coder I would be happy to help.  Either with HTML Emails or in another capacity.

Thanks,
Ryan

**Comment by jasonrhodes** [comment]
Hey everyone, I went ahead and made a very simple update to the homepage and cloned a previous event for the ti.to page, so registration is live. http://ti.to/baltimorenodeschool/four

If anyone is interested in using the info on those pages to draft an announcement email, send it over, otherwise I'll draft that tonight and send it out tomorrow, probably.

Key takeaways:

* We're doing Learn You Node as always, plus Javascripting for people who want to learn JS and Stream Adventure for advanced folks. This is the first time we've done 3, and I'm not sure how good Javascripting is for new people, but we're gonna give it all a spin.
* I'm trying a new thing with http://nodeschool.io/baltimore#before, which is meant to 
  - Prepare people before they come, and
  - Do stuff
* I'm going to do a 30 minute setup/Q&A session *before* the event starts, which I'd love mentor help to run. Just an open-ended session to allow people who may be unsure about the event to come and get some help in advance. Let me know if you have ideas about this or if you can show up for it.

**Comment by unstoppablecarl** [comment]
I think the before session is a good idea I would be happy to be there.

**Comment by unstoppablecarl** [comment]
@jasonrhodes snap your pixels in this image http://nodeschool.io/baltimore/assets/images/bmorenodeschool-white.png
you are better than this.

**Comment by jasonrhodes** [comment]
@unstoppablecarl I don't know what those words mean.

**Comment by jasonrhodes** [comment]
More importantly, pull requests welcome... ;)

**Comment by unstoppablecarl** [comment]
The text in that image is blocky, but the edges of it are burred when they should be solid all around.

**Comment by jasonrhodes** [comment]
FYI that text is a font: https://github.com/potch/8bitArtSans

**Comment by mikeriley131** [comment]
Thanks, Jason.

Do you know the times for the event? Could you list those on the
registration page?

**Comment by jasonrhodes** [comment]
Sure, @mikeriley131 -- I updated the page and linked to the 3 courses we'll be offering.

There is also a link to our website, which has all the information:
http://nodeschool.io/baltimore/

**Comment by mikeriley131** [comment]
That's great! Thanks Jason.
