### ISSUE TITLE
Should replace instances of Jason's email with link to join our slack

### ISSUE THREAD

**Issue by mike-zorn** [nodeschool/baltimore#12]
@jasonrhodes, which channels should we have for people to leave nodeschool feedback, voice concerns before attending? Alternatively, should we just keep it as your email.

**Comment by jasonrhodes** [comment]
Not sure exactly how to handle this. Happy to get my personal email out of there, but "sign up for slack and find us there" seems like a lot more work. We have a baltimorenodeschool@gmail address but would have to set that up to forward to people or something... I am definitely overthinking it but not sure the best solution there :)

**Comment by mike-zorn** [comment]
Yeah, that's a good point: the barrier to ask a question and leave feedback should be lower than joining slack. We could set up a [slack-email integration](http://slackhq.com/post/126629257535/email) so that we don't have to worry about getting people access to that email account.
