### ISSUE TITLE
Getting Up and Running Again 2015

### ISSUE THREAD

**Issue by jasonrhodes** [nodeschool/baltimore#9]
Related issues: #5 #8

OK, I got killed by the holidays and things didn't come together for a number of reasons at the end of last year, so we've been off for a while, but I want to get started up again. We should plan another regular event for ASAP but I also want to be thinking about a few things:

* How do we provide a better on-boarding experience for people who are newer to programming and get stuck in the early lessons of Learn You Node in what they describe as a frustrating way? We tried pushing a few people to Codecademy at our least event but I really think we could do better.
* How do we market the event so that people who have _no experience_ with any kind of computer coding or markup, etc. will know that this is probably not a good fit for them? I want to help everyone get excited about JavaScript and Node.js but I think there's a limit to what we can do with the format we are running, and if you don't have a text editor and don't really know what JS is at all, I think there are probably better options for you. Maybe prerequisites, in a more casual sense?
* How do we start giving back to the OSS NodeSchool community? I'd like people to file bugs against the workshoppers we do, leave comments about what could be improved, and even start submitting Pull Requests to fix them. I'd even like it if we could start contributing new workshopper lessons back to the community, or updating the main website, or creating tools for other chapter organizers. This is how Open Source works, let's give back!

In the interest of figuring this out, I'm going to set up something in February for people interested in helping with NodeSchool in any way to help me brainstorm and think through some of these ideas. Stay tuned for more info about this, I think I may do it over Google Hangouts or in gitter, something that doesn't require us to all get together yet again. 

Simultaneously let's plan our next regular workshopper event for late Feb/early March, on a Sunday afternoon because that seems to have worked the best. @shawngrimes is DHF still available and can you suggest what Sundays are available in late Feb/early March?

**Comment by shawngrimes** [comment]
DHF is always happy to host Baltimore Node School.

Looking at the calendar, here are some options for Sundays:
Feb. 8th
Feb 15th
Mar 29th

The Sundays below are also available, I would just have to get another staff member to cover them because I am personally not available.  That's not a problem at all since a few of our staff want to actually attend this time around.
Feb. 22nd
Mar 15th
Mar 22nd

**Comment by jmartin4563** [comment]
All of the sundays that Shawn mentioned should work for me, pretty much anything that's not the first week of March (as I'll probably be jetlagged from the ride back from ng-conf)

**Comment by jasonrhodes** [comment]
I'm leaning toward March 15

**Comment by jmartin4563** [comment]
Does it get crazy in bmore for the St. Patrick's Day Parade? According to their page it starts @ 2pm so we might miss the brunt of it?

**Comment by jasonrhodes** [comment]
WELP can't do March 15 then good call @jmartin4563 -- my wife is running that 5k. :gulp: close one

**Comment by bizob2828** [comment]
3/22

**Comment by bizob2828** [comment]
I'm in too

**Comment by richleland** [comment]
I second 3/22. Count me in.

**Comment by dheles** [comment]
I would like to help out. So far, I have no Sundays in February, but all the Sundays in March available.

Might the javacripting workshopper ( https://github.com/sethvincent/javascripting ) be useful for addressing Jason's first point (and possibly second, as a "try this at home to see if this event is a good fit for you")?

**Comment by shawngrimes** [comment]
I'll put a hold on 3/22 for you but happy to throw out more dates if needed.

**Comment by timnoel1** [comment]
I should be able to help out on 3/22.  I'm in.

**Comment by jasonrhodes** [comment]
Yes, tentatively let's go with 3/22 and I'll know for sure in a few days.
Thanks, Shawn!

**Comment by jasonrhodes** [comment]
OK @everyone here, 3/22 doesn't work for me either because of previously scheduled stuff I wasn't aware of. Unless I hear lots of objections in the next day or so, I'm going to schedule us for Sunday 3/29. 

Sorry for the back and forth. Next I'll post some of my thoughts about format changes in a separate issue.

**Comment by jasonrhodes** [comment]
Alright, no complaints so 3/29 it is. (@shawngrimes just a final confirm with you that DHF is still available that day from around 11-5?) 

Stay tuned for a new issue for the things I'll need help taking care of soon.

**Comment by shawngrimes** [comment]
Confirmed, we are available and I have that day on hold for you.
